// config/smsCost/config.js

// Pricing data from https://help.genesys.cloud/articles/sms-monthly-recurring-pricing/
// Using USD as the currency.
const MRP_PRICING_USD = {
    "A": 1.25,
    "B": 2.50,
    "C": 1.25,
    "D": 3.75,
    "E": 6.25,
    "F": 7.50,
    "G": 12.50,
    "H": 18.00,
    "I": 35.00,
    "J": 93.75
};

const INBOUND_SMS_PRICING_USD = {
  'A': 0.01,
  'B': 0.01,
  'D': 0.05,
  'C': 0.03,
  'E': 0.06
};

const OUTBOUND_SMS_PRICING_USD = {
  'A': 0.01,
  'B': 0.0125,
  'O': 0.2,
  'L': 0.12,
  'K': 0.11,
  'Q': 0.4,
  'G': 0.07,
  'N': 0.15,
  'M': 0.13,
  'F': 0.06,
  'E': 0.05,
  'P': 0.3,
  'C': 0.03,
  'UNKNOWN': 0.03,
  'H': 0.08,
  'I': 0.09,
  'D': 0.04,
  '0': 0.2,
  'J': 0.1
};

// Mapping from country and type to rate class (using 2-character country codes)
const countryTypeToRateClass = {
    "US": { "local": "A", "mobile": "A", "tollfree": "B" },
    "CA": { "local": "A", "mobile": "A", "tollfree": "B" },
    "AU": { "default": "F" },
    "AT": { "default": "F" },
    "BE": { "default": "C" },
    "CL": { "default": "G" },
    "HR": { "default": "F" },
    "CZ": { "default": "H" },
    "DK": { "default": "H" },
    "EE": { "default": "D" },
    "FR": { "default": "D" },
    "DE": { "default": "E" },
    "HK": { "default": "H" },
    "HU": { "default": "I" },
    "IE": { "default": "F" },
    "IL": { "default": "H" },
    "IT": { "default": "I" },
    "LT": { "default": "D" },
    "MY": { "default": "E" },
    "NL": { "default": "E" },
    "PL": { "default": "D" },
    "PT": { "default": "H" },
    "PR": { "default": "D" },
    "SG": { "default": "J" },
    "ES": { "default": "E" },
    "CH": { "default": "G" },
    "GB": { "default": "C" }
};

const numberToDivisionMap = {};

const countryTypeToRateClassOutbound = {
  "US": { "local": "A", "toll-free": "A" },
  "CA": { "local": "B", "toll-free": "B" },
  "AS": { "local": "O" },
  "AF": { "local": "L" },
  "AL": { "local": "K" },
  "DZ": { "local": "Q" },
  "AD": { "local": "O" },
  "AO": { "local": "G" },
  "AI": { "local": "N" },
  "AG": { "local": "N" },
  "AR": { "local": "K" },
  "AW": { "local": "N" },
  "AM": { "local": "O" },
  "AU": { "local": "G" },
  "AT": { "local": "M" },
  "AZ": { "local": "Q" },
  "BS": { "local": "F" },
  "BH": { "local": "E" },
  "BD": { "local": "Q" },
  "BB": { "local": "O" },
  "BY": { "local": "P" },
  "BZ": { "local": "P" },
  "BJ": { "local": "P" },
  "BE": { "local": "N" },
  "BM": { "local": "O" },
  "BT": { "local": "Q" },
  "BO": { "local": "O" },
  "BA": { "local": "K" },
  "BW": { "local": "L" },
  "BN": { "local": "UNKNOWN" },
  "BR": { "local": "H" },
  "VG": { "local": "P" },
  "BG": { "local": "O" },
  "BF": { "local": "O" },
  "BI": { "local": "Q" },
  "KH": { "local": "O" },
  "CM": { "local": "P" },
  "CV": { "local": "P" },
  "KY": { "local": "O" },
  "CF": { "local": "C" },
  "TD": { "local": "P" },
  "CL": { "local": "I" },
  "CN": { "local": "F" },
  "CK": { "local": "D" },
  "KM": { "local": "Q" },
  "CG": { "local": "P" },
  "CO": { "local": "M" },
  "CR": { "local": "F" },
  "HR": { "local": "L" },
  "CU": { "local": "K" },
  "CY": { "local": "K" },
  "CZ": { "local": "G" },
  "DK": { "local": "F" },
  "DJ": { "local": "O" },
  "DM": { "local": "O" },
  "CD": { "local": "E" },
  "DO": { "local": "I" },
  "TL": { "local": "L" },
  "EC": { "local": "O" },
  "EG": { "local": "P" },
  "SV": { "local": "M" },
  "GQ": { "local": "D" },
  "ER": { "local": "M" },
  "EE": { "local": "L" },
  "ET": { "local": "Q" },
  "FK": { "local": "I" },
  "FO": { "local": "K" },
  "FJ": { "local": "P" },
  "FI": { "local": "K" },
  "FR": { "local": "K" },
  "GF": { "local": "N" },
  "PF": { "local": "P" },
  "GA": { "local": "Q" },
  "GM": { "local": "O" },
  "GE": { "local": "O" },
  "DE": { "local": "K" },
  "GH": { "local": "P" },
  "GI": { "local": "N" },
  "GR": { "local": "H" },
  "GL": { "local": "E" },
  "GD": { "local": "P" },
  "GP": { "local": "O" },
  "GU": { "local": "I" },
  "GT": { "local": "P" },
  "GG": { "local": "D" },
  "GN": { "local": "O" },
  "GW": { "local": "K" },
  "GY": { "local": "P" },
  "HT": { "local": "P" },
  "HN": { "local": "O" },
  "HK": { "local": "H" },
  "HU": { "local": "L" },
  "IS": { "local": "J" },
  "IN": { "local": "H" },
  "IR": { "local": "Q" },
  "IQ": { "local": "Q" },
  "ID": { "local": "Q" },
  "IE": { "local": "I" },
  "IL": { "local": "0" },
  "IT": { "local": "K" },
  "CI": { "local": "UNKNOWN" },
  "JM": { "local": "P" },
  "JP": { "local": "K" },
  "JE": { "local": "E" },
  "JO": { "local": "P" },
  "KZ": { "local": "O" },
  "KE": { "local": "O" },
  "KI": { "local": "J" },
  "KV": { "local": "UNKNOWN" },
  "KW": { "local": "P" },
  "KG": { "local": "Q" },
  "LA": { "local": "P" },
  "LV": { "local": "J" },
  "LB": { "local": "Q" },
  "LS": { "local": "P" },
  "LR": { "local": "P" },
  "LY": { "local": "Q" },
  "LI": { "local": "E" },
  "LT": { "local": "G" },
  "LU": { "local": "I" },
  "MO": { "local": "H" },
  "MK": { "local": "J" },
  "MC": { "local": "P" },
  "MW": { "local": "P" },
  "MY": { "local": "O" },
  "MV": { "local": "P" },
  "ML": { "local": "Q" },
  "MT": { "local": "H" },
  "MQ": { "local": "O" },
  "MH": { "local": "O" },
  "MU": { "local": "P" },
  "MF": { "local": "K" },
  "MX": { "local": "H" },
  "FM": { "local": "I" },
  "MD": { "local": "J" },
  "MN": { "local": "Q" },
  "ME": { "local": "N" },
  "MS": { "local": "F" },
  "MA": { "local": "P" },
  "MZ": { "local": "P" },
  "MM": { "local": "P" },
  "NP": { "local": "P" },
  "NL": { "local": "L" },
  "AN": { "local": "F" },
  "NC": { "local": "P" },
  "NZ": { "local": "M" },
  "NI": { "local": "J" },
  "NU": { "local": "B" },
  "NE": { "local": "Q" },
  "NG": { "local": "P" },
  "MP": { "local": "UNKNOWN" },
  "NF": { "local": "D" },
  "NO": { "local": "H" },
  "OM": { "local": "O" },
  "PK": { "local": "Q" },
  "PW": { "local": "M" },
  "PS": { "local": "Q" },
  "PA": { "local": "O" },
  "PG": { "local": "Q" },
  "PY": { "local": "L" },
  "PE": { "local": "L" },
  "PH": { "local": "P" },
  "PL": { "local": "F" },
  "PT": { "local": "F" },
  "PR": { "local": "F" },
  "QA": { "local": "P" },
  "RO": { "local": "J" },
  "RE": { "local": "P" },
  "RU": { "local": "Q" },
  "RW": { "local": "P" },
  "WS": { "local": "Q" },
  "ST": { "local": "K" },
  "SA": { "local": "M" },
  "SM": { "local": "K" },
  "SN": { "local": "Q" },
  "RS": { "local": "P" },
  "SC": { "local": "G" },
  "SL": { "local": "P" },
  "SG": { "local": "F" },
  "SK": { "local": "K" },
  "SO": { "local": "Q" },
  "SB": { "local": "J" },
  "ZA": { "local": "H" },
  "KR": { "local": "F" },
  "SS": { "local": "P" },
  "ES": { "local": "K" },
  "LK": { "local": "Q" },
  "KN": { "local": "O" },
  "LC": { "local": "O" },
  "PM": { "local": "P" },
  "VC": { "local": "P" },
  "SD": { "local": "P" },
  "SR": { "local": "P" },
  "SZ": { "local": "M" },
  "SE": { "local": "H" },
  "CH": { "local": "I" },
  "SY": { "local": "H" },
  "TW": { "local": "G" },
  "TJ": { "local": "G" },
  "TZ": { "local": "O" },
  "TH": { "local": "D" },
  "TG": { "local": "O" },
  "TO": { "local": "G" },
  "TT": { "local": "P" },
  "TN": { "local": "Q" },
  "TR": { "local": "D" },
  "TC": { "local": "O" },
  "TM": { "local": "L" },
  "TV": { "local": "M" },
  "UA": { "local": "O" },
  "UG": { "local": "P" },
  "AE": { "local": "D" },
  "GB": { "local": "E" },
  "UY": { "local": "J" },
  "UZ": { "local": "Q" },
  "VU": { "local": "P" },
  "VE": { "local": "L" },
  "VN": { "local": "O" },
  "VI": { "local": "C" },
  "YE": { "local": "Q" },
  "ZM": { "local": "Q" },
  "ZW": { "local": "P" }
};

export {
    MRP_PRICING_USD,
    countryTypeToRateClass,
    numberToDivisionMap,
    INBOUND_SMS_PRICING_USD,
    OUTBOUND_SMS_PRICING_USD,
    countryTypeToRateClassInbound,
    countryTypeToRateClassOutbound,
};
